apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-davulv
  namespace: davulv
  labels:
    type: local
spec:
  storageClassName: mysql-davulv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-davulv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-davulv
namespace: davulv
spec:
  storageClassName: mysql-davulv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
